language: julia
os:
   - linux
   - osx
julia:
   - 0.3
   - 0.4
   - nightly
after_success:
   - if [ $TRAVIS_JULIA_VERSION != "0.3" ]; then julia -e 'cd(Pkg.dir("ArrayViews")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
notifications:
  email: false
